import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "../styles/root.scss";
import TopHeader from "@/components/common/TopHeader";
import Footer from "@/components/common/Footer";

const lexend = Lexend({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <TopHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
